-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-03-20 11:29:06 EDT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



CREATE USER ud_jbeans IDENTIFIED BY ACCOUNT UNLOCK ;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ud_jbeans.countries (
    country_id   CHAR(2 BYTE) NOT NULL,
    country_name VARCHAR2(40 BYTE),
    region_id    NUMBER
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX ud_jbeans.countries_pk ON
    ud_jbeans.countries (
        country_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE ud_jbeans.countries
    ADD CONSTRAINT country_c_id_pk PRIMARY KEY ( country_id )
        USING INDEX ud_jbeans.countries_pk;

CREATE TABLE ud_jbeans.departments (
    department_id   NUMBER(4) NOT NULL,
    department_name VARCHAR2(30 BYTE) NOT NULL,
    manager_id      NUMBER(6),
    location_id     NUMBER(4)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX ud_jbeans.departments_pk ON
    ud_jbeans.departments (
        department_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE ud_jbeans.departments
    ADD CONSTRAINT departments_pk PRIMARY KEY ( department_id )
        USING INDEX ud_jbeans.departments_pk;

CREATE TABLE ud_jbeans.employees (
    employee_id    NUMBER(6) NOT NULL,
    first_name     VARCHAR2(20 BYTE),
    last_name      VARCHAR2(25 BYTE) NOT NULL,
    email          VARCHAR2(25 BYTE) NOT NULL,
    phone_number   VARCHAR2(20 BYTE),
    hire_date      DATE NOT NULL,
    job_id         VARCHAR2(10 BYTE) NOT NULL,
    salary         NUMBER(8, 2),
    commission_pct NUMBER(2, 2),
    manager_id     NUMBER(6),
    department_id  NUMBER(4)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX ud_jbeans.employees_pk ON
    ud_jbeans.employees (
        employee_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

CREATE UNIQUE INDEX ud_jbeans.employees_uk1 ON
    ud_jbeans.employees (
        email
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE ud_jbeans.employees
    ADD CONSTRAINT employees_pk PRIMARY KEY ( employee_id )
        USING INDEX ud_jbeans.employees_pk;

ALTER TABLE ud_jbeans.employees
    ADD CONSTRAINT emp_email_uk UNIQUE ( email )
        USING INDEX ud_jbeans.employees_uk1;

CREATE TABLE ud_jbeans.job_history (
    employee_id   NUMBER(6) NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    job_id        VARCHAR2(20 BYTE) NOT NULL,
    department_id NUMBER(4)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX ud_jbeans.job_history_pk ON
    ud_jbeans.job_history (
        employee_id
    ASC,
        start_date
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE ud_jbeans.job_history
    ADD CONSTRAINT job_history_pk PRIMARY KEY ( employee_id,
                                                start_date )
        USING INDEX ud_jbeans.job_history_pk;

CREATE TABLE ud_jbeans.jobs (
    job_id     VARCHAR2(10 BYTE) NOT NULL,
    job_title  VARCHAR2(35 BYTE) NOT NULL,
    min_salary NUMBER(6),
    max_salary NUMBER(6)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX ud_jbeans.jobs_pk ON
    ud_jbeans.jobs (
        job_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE ud_jbeans.jobs
    ADD CONSTRAINT jobs_id_pk PRIMARY KEY ( job_id )
        USING INDEX ud_jbeans.jobs_pk;

CREATE TABLE ud_jbeans.locations (
    location_id    NUMBER(4) NOT NULL,
    street_address VARCHAR2(40 BYTE),
    postal_code    VARCHAR2(12 BYTE),
    city           VARCHAR2(30 BYTE) NOT NULL,
    state_province VARCHAR2(25 BYTE),
    country_id     CHAR(2 BYTE)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX ud_jbeans.locations_pk ON
    ud_jbeans.locations (
        location_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE ud_jbeans.locations
    ADD CONSTRAINT loc_id_pk PRIMARY KEY ( location_id )
        USING INDEX ud_jbeans.locations_pk;

CREATE TABLE ud_jbeans.regions (
    region_id   NUMBER NOT NULL,
    region_name VARCHAR2(25 BYTE)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

CREATE UNIQUE INDEX ud_jbeans.regions_pk ON
    ud_jbeans.regions (
        region_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE ud_jbeans.regions
    ADD CONSTRAINT reg_id_pk PRIMARY KEY ( region_id )
        USING INDEX ud_jbeans.regions_pk;

ALTER TABLE ud_jbeans.countries
    ADD CONSTRAINT countr_reg_fk FOREIGN KEY ( region_id )
        REFERENCES ud_jbeans.regions ( region_id )
    NOT DEFERRABLE;

ALTER TABLE ud_jbeans.departments
    ADD CONSTRAINT dept_loc_fk FOREIGN KEY ( location_id )
        REFERENCES ud_jbeans.locations ( location_id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ud_jbeans.departments
    ADD CONSTRAINT dept_mgr_fk FOREIGN KEY ( manager_id )
        REFERENCES ud_jbeans.employees ( employee_id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ud_jbeans.employees
    ADD CONSTRAINT emp_dept_fk FOREIGN KEY ( department_id )
        REFERENCES ud_jbeans.departments ( department_id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ud_jbeans.employees
    ADD CONSTRAINT emp_job_fk FOREIGN KEY ( job_id )
        REFERENCES ud_jbeans.jobs ( job_id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ud_jbeans.employees
    ADD CONSTRAINT emp_manager_fk FOREIGN KEY ( manager_id )
        REFERENCES ud_jbeans.employees ( employee_id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ud_jbeans.job_history
    ADD CONSTRAINT jhist_dept_fk FOREIGN KEY ( department_id )
        REFERENCES ud_jbeans.departments ( department_id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ud_jbeans.job_history
    ADD CONSTRAINT jhist_emp_fk FOREIGN KEY ( employee_id )
        REFERENCES ud_jbeans.employees ( employee_id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ud_jbeans.job_history
    ADD CONSTRAINT jhist_job_fk FOREIGN KEY ( job_id )
        REFERENCES ud_jbeans.jobs ( job_id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ud_jbeans.locations
    ADD CONSTRAINT loc_c_id_fk FOREIGN KEY ( country_id )
        REFERENCES ud_jbeans.countries ( country_id )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             8
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
